{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.controller.enabled true -}}
apiVersion: {{ include "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "lighthouse.controller.clusterrole.name" . }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
{{- end }}