{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq (include "lighthouse.controller.enabled" .) "true" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lighthouse.controller.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lighthouse.controller.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.server.replicaCount }}
  revisionHistoryLimit: {{ .Values.server.revisionHistoryLimit }}
  template:
    metadata:
      labels:
         {{- include "lighthouse.controller.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lighthouse.controller.serviceAccount.name" .  }}
      containers:
        - image: {{ include "lighthouse.controller.image.repository" . }}:{{ .Values.server.image.tag }}
          imagePullPolicy: {{ include "lighthouse.controller.image.pullPolicy" .  }}
          name: lighthouse-controller
          env:
            - name: "IS_K8"
              value: "TRUE"
          envFrom:
            - configMapRef:
                name: {{ include "lighthouse.controller.configmap.name" . }}
            - secretRef:
                name: {{ include "lighthouse.controller.secret.name" . }}
          {{- if .Values.server.resources }}
          resources: {{- toYaml .Values.server.resources | nindent 12 }}
          {{- else if .Values.global.resources }}
          resources: {{- toYaml .Values.global.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.targetPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.server.grpc.targetPort }}
              protocol: TCP
{{- end }}