{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if and (eq .Values.controller.enabled true) (eq .Values.controller.ingress.enabled true) -}}
apiVersion: {{ .Values.controller.ingress.apiVersion | default (include "ingress.apiVersion" .) }}
kind: Ingress
metadata:
  name: {{ include "lighthouse.controller.ingress.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.controller.labels" . | nindent 4 }}
  {{- if or (.Values.controller.ingress.annotations) (.Values.controller.ingress.annotations) }}
  annotations:
     {{- $annotations := .Values.controller.ingress.annotations | default .Values.global.ingress.annotations }}
     {{- range $key, $value := $annotations }}
     {{ $key }}: {{ $value | quote }}
     {{- end }}
  {{- end }}
spec:
    {{- if or (.Values.controller.ingress.ingressClassName) (.Values.global.ingress.ingressClassName) }}
  ingressClassName: {{ .Values.controller.ingress.ingressClassName | default .Values.global.ingress.ingressClassName | toString | quote }}
    {{- end }}
  rules:
      {{- if .Values.controller.ingress.hostname }}
    - host: {{ .Values.controller.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.controller.ingress.path }}
              {{- if eq "true" (include "ingress.supportsPathType" .) }}
            pathType: {{ .Values.controller.ingress.pathType | default .Values.global.ingress.pathType }}
              {{- end }}
            backend: {{- include "ingress.backend" (dict "ingressApiVersion" (.Values.controller.ingress.apiVersion | default (include "ingress.apiVersion" .)) "serviceName" (include "lighthouse.controller.name" .) "servicePort" .Values.controller.service.port . $)  | nindent 14 }}
      {{- end }}
    {{- if eq .Values.controller.ingress.tls.enabled true }}
  tls:
    - hosts:
        - {{ .Values.controller.ingress.hostname }}
      secretName: {{ include "lighthouse.controller.ingress.tls.secretName" . }}
    {{- end }}
{{- end }}
