{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.controller.enabled true -}}
apiVersion: {{ include "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name:  {{ include "lighthouse.controller.role.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lighthouse.controller.serviceAccount.name" . }}
    namespace: {{ include "lighthouse.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "lighthouse.controller.role.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}