{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.controller.enabled true -}}
apiVersion: {{ include "rbac.apiVersion" . }}
kind: Role
metadata:
  name:  {{ include "lighthouse.controller.role.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch", "create", "update", "delete", "get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "list", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "list", "update", "watch", "delete", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch", "delete", "get"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["list", "watch", "delete", "get"]
{{- end }}