{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq (include "lighthouse.controller.enabled" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.controller.secret.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.controller.labels" . | nindent 4 }}
data:
  JWT_SECRET: {{ randAlphaNum 40 | toString | b64enc | quote}}
  JWT_REFRESH_SECRET: {{ randAlphaNum 15 | toString | b64enc | quote}}
  USER_EMAIL: {{ include "lighthouse.user.email" .  | toString | b64enc | quote}}
  PASSWORD: {{  include "lighthouse.user.password" .  | toString | b64enc | quote}}
  MONGO_URI: {{ include "lighthouse.db.mongo.uri" . | toString | b64enc | quote }}
{{- end }}
