{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq (include "lighthouse.controller.enabled" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse.controller.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.server.grpc.port }}
      targetPort: {{ .Values.server.grpc.targetPort }}
      protocol: TCP
      name: grpc
  selector:
      {{- include "lighthouse.controller.selectorLabels" . | nindent 4 }}
{{- end }}