{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if and (eq .Values.controller.enabled true) (eq .Values.controller.ingress.enabled true) -}}
{{- if and (eq .Values.controller.ingress.tls.enabled true) (and (empty .Values.controller.ingress.tls.secretName) (empty .Values.global.ingress.tls.secretName)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.controller.ingress.tls.secretName" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.controller.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if not (empty (include "lighthouse.controller.ingress.tls.crt" .)) }}
  tls.crt: {{ include "lighthouse.controller.ingress.tls.crt" . | b64enc | quote }}
  {{- end }}
  {{- if not (empty (include "lighthouse.controller.ingress.tls.key" .)) }}
  tls.key: {{ include "lighthouse.controller.ingress.tls.key" . | b64enc | quote }}
  {{- end }}
  {{- if not (empty (include "lighthouse.controller.ingress.tls.ca" .)) }}
  ca.crt: {{ include "lighthouse.controller.ingress.tls.ca" . | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
