{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if and (eq (include "lighthouse.controller.enabled" .) "true") (eq .Values.db.mongo.create true) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.db.mongo.secretName" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.db.mongo.labels" . | nindent 4 }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ include "lighthouse.db.mongo.rootUsername" .  | toString | b64enc | quote}}
  MONGO_INITDB_ROOT_PASSWORD: {{ include "lighthouse.db.mongo.rootPassword" .  | toString | b64enc | quote}}
{{- end }}