{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if and (eq (include "lighthouse.controller.enabled" .) "true") (eq .Values.db.mongo.create true) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lighthouse.db.mongo.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.db.mongo.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "lighthouse.db.mongo.headlessServiceName" . }}
  replicas: {{ .Values.db.mongo.replicaCount }}
  selector:
    matchLabels:
      {{- include "lighthouse.db.mongo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lighthouse.db.mongo.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lighthouse.controller.serviceAccount.name" .  }}
      containers:
        - name: {{ include "lighthouse.db.mongo.name" . }}
          image: {{ .Values.db.mongo.image.repository }}:{{ .Values.db.mongo.image.tag }}
          imagePullPolicy: {{ .Values.db.mongo.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.db.mongo.targetPort }}
          envFrom:
            - secretRef:
                name: {{ include "lighthouse.db.mongo.secretName" . }}
          volumeMounts:
            - name: {{ include "lighthouse.db.mongo.persistence.name" . }}
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: {{ include "lighthouse.db.mongo.persistence.name" . }}
        namespace: {{ include "lighthouse.namespace" . }}
        labels:
          {{- include "lighthouse.db.mongo.labels" . | nindent 10 }}
        {{- if .Values.db.mongo.persistence.annotations }}
        annotations:
         {{- $annotations := .Values.db.mongo.persistence.annotations }}
         {{- range $key, $value := $annotations }}
         {{ $key }}: {{ $value | quote }}
         {{- end }}
        {{- end }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.db.mongo.persistence.size | quote }}
        {{- if not (empty .Values.db.mongo.persistence.storageClassName) }}
        storageClassName: {{ .Values.db.mongo.persistence.storageClassName | quote }}
        {{- end }}
{{- end }}