{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.agent.enabled true -}}
apiVersion: {{ include "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "lighthouse.agent.clusterrolebinding.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lighthouse.agent.clusterrole.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lighthouse.agent.serviceAccount.name" . }}
    namespace: {{ include "lighthouse.namespace" . }}
{{- end }}