{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.agent.enabled true -}}
apiVersion: {{ include "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "lighthouse.agent.clusterrole.name" . }}
  labels:
    {{- include "lighthouse.agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
{{- end }}