{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if and (eq .Values.agent.enabled true) (.Values.auth.token) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.agent.secret.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.agent.labels" . | nindent 4 }}
data:
  AUTH_TOKEN: {{ .Values.auth.token | toString | b64enc | quote}}
{{- end }}