{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if and (eq .Values.agent.enabled true) (not (empty .Values.config.controller.grpc.tls.ca)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.agent.secret.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.agent.labels" . | nindent 4 }}
data:
  TLS_SERVER_CUSTOM_CA: {{ .Values.config.controller.grpc.tls.ca | b64enc | quote }}
---
{{- end }}
{{- if and (eq .Values.agent.enabled true) (not (empty .Values.auth.token)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.agent.auth.secret.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.agent.labels" . | nindent 4 }}
data:
  AUTH_TOKEN: {{ .Values.auth.token | toString | b64enc | quote}}
  AGENT_GROUP: {{ include "lighthouse.agent.wrokerGroup" . | toString | b64enc | quote }}
{{- end }}