{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.agent.enabled true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lighthouse.agent.serviceAccount.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
{{- end }}