{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lighthouse.clusterrolebinding.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lighthouse.clusterrole.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lighthouse.serviceAccount.name" . }}
    namespace: {{ include "lighthouse.namespace" . }}
