{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lighthouse.serviceAccount.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}