{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.controller.enabled true -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: lighthouse-cleanup-job
  namespace: {{ include "lighthouse.namespace" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "lighthouse.controller.serviceAccount.name" . }}
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command:
            - /bin/sh
            - -c
            - |
              echo "Cleaning up orphan resources..."
              {{- if eq .Values.db.mongo.create true -}}
              echo "Checking and deleting DB..."
              if kubectl get sts {{ include "lighthouse.db.mongo.name" . }} -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                echo "Deleting Secrets..."
                kubectl delete sts {{ include "lighthouse.db.mongo.name" . }} -n {{ .Release.Namespace }}
              else
                echo "No DB StatefulsSet found. Skipping deletion."
              fi

              echo "Checking and deleting PVCs..."
              if kubectl get pvc -l app.kubernetes.io/name={{ printf "lighthouse" }} -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                echo "Deleting Secrets..."
                kubectl delete pvc -l app.kubernetes.io/name={{ printf "lighthouse" }} -n {{ .Release.Namespace }}
              else
                echo "No PVC found. Skipping deletion."
              fi
              {{- end }}
              echo "Checking for Secrets..."
              if kubectl get secret {{ include "lighthouse.agent.secret.name" . }} -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                echo "Deleting Secrets..."
                kubectl delete secret {{ include "lighthouse.agent.secret.name" . }} -n {{ .Release.Namespace }}
              else
                echo "No Secrets found. Skipping deletion."
              fi
{{- end }}