{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.controller.enabled true -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lighthouse.webapp.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.webapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lighthouse.webapp.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.controller.webapp.replicaCount }}
  revisionHistoryLimit: {{ .Values.controller.webapp.revisionHistoryLimit }}
  template:
    metadata:
      labels:
         {{- include "lighthouse.webapp.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lighthouse.controller.serviceAccount.name" .  }}
      containers:
        - image: {{ include "lighthouse.webapp.image.repository" . }}:{{ include "lighthouse.webapp.image.tag" . }}
          imagePullPolicy: {{ include "lighthouse.webapp.image.pullPolicy" .  }}
          name: lighthouse-webapp
          envFrom:
            - configMapRef:
                name: {{ include "lighthouse.webapp.configmap.name" . }}
          {{- if .Values.controller.webapp.resources }}
          resources: {{- toYaml .Values.controller.webapp.resources | nindent 12 }}
          {{- else if .Values.global.resources }}
          resources: {{- toYaml .Values.global.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.controller.webapp.service.targetPort }}
              protocol: TCP
{{- end }}