{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if eq .Values.controller.enabled true -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse.webapp.name" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.webapp.service.type }}
  ports:
    - port: {{ .Values.controller.webapp.service.port }}
      targetPort: {{ .Values.controller.webapp.service.targetPort }}
      protocol: TCP
      name: http
  selector:
      {{- include "lighthouse.webapp.selectorLabels" . | nindent 4 }}
{{- end }}