{{- /*
  Copyright Krack8, Inc. All Rights Reserved.
*/}}
{{- if and (eq (include "lighthouse.controller.enabled" .) "true") (eq .Values.server.webapp.ingress.enabled true) -}}
{{- if and (eq .Values.server.webapp.ingress.tls.enabled true)
(and (.Values.server.webapp.ingress.tls.crt) (.Values.global.ingress.tls.key))
(and (empty .Values.server.webapp.ingress.tls.secretName) (empty .Values.global.ingress.tls.secretName)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.webapp.ingress.tls.secretName" . }}
  namespace: {{ include "lighthouse.namespace" . }}
  labels:
    {{- include "lighthouse.webapp.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if not (empty (include "lighthouse.webapp.ingress.tls.crt" .)) }}
  tls.crt: {{ include "lighthouse.webapp.ingress.tls.crt" . | b64enc | quote }}
  {{- end }}
  {{- if not (empty (include "lighthouse.webapp.ingress.tls.key" .)) }}
  tls.key: {{ include "lighthouse.webapp.ingress.tls.key" . | b64enc | quote }}
  {{- end }}
  {{- if not (empty (include "lighthouse.webapp.ingress.tls.ca" .)) }}
  ca.crt: {{ include "lighthouse.webapp.ingress.tls.ca" . | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
